name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install requirements
      run: sudo apt update && sudo apt -y upgrade && pip install -r requirements.txt
    - name: run service
      run: nohup python3 app.py &
    - name: get health
      run: curl localhost:9001/health