name: Continuous Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_HOST }}
    - name: Git Pull
      run: ssh ubuntu@3.208.17.116 "cd ~/E6156_Composite && git pull && nohup python3 app.py & && clear"